create table monthly_summaries (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  month date not null,
  total_income numeric default 0,
  total_expenses numeric default 0,
  savings_amount numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
alter table monthly_summaries enable row level security;

create policy "Users can view their own monthly summaries"
on monthly_summaries for select
using ( auth.uid() = user_id );

create policy "Users can insert their own monthly summaries"
on monthly_summaries for insert
with check ( auth.uid() = user_id );

create policy "Users can update their own monthly summaries"
on monthly_summaries for update
using ( auth.uid() = user_id );
