-- Create plant_species_care_guides table
CREATE TABLE plant_species_care_guides (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  species_name TEXT NOT NULL UNIQUE,
  variety TEXT, -- Optional, for specific varieties if needed later
  
  -- Care information generated by AI
  care_level TEXT, -- e.g., "Easy", "Moderate"
  climate TEXT, -- e.g., "warm, sunny"
  watering_frequency TEXT, -- e.g., "2-3 times a week"
  fertilizer_frequency TEXT, -- e.g., "Every 2 weeks"
  pruning_info TEXT,
  companions TEXT, -- e.g., "Basil, Marigold"
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_care_guides_species ON plant_species_care_guides(species_name);

-- Enable RLS
ALTER TABLE plant_species_care_guides ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- Everyone can read care guides
CREATE POLICY "Public read access for care guides"
  ON plant_species_care_guides FOR SELECT
  USING (true);

-- Only service role (and maybe authenticated users if we crackdown) can insert/update
-- For now, letting authenticated users insert is fine if triggered by the Edge Function 
-- (which runs as service role usually, but let's allow auth users to be safe for now or restriction appropriately)
-- Actually, edge function should use service_role key to write to this table if we want to restrict it from random user edits.
-- But standard policy:
CREATE POLICY "Service role can manage care guides"
  ON plant_species_care_guides
  USING ( auth.role() = 'service_role' )
  WITH CHECK ( auth.role() = 'service_role' );
  
-- Allow authenticated users to insert if it doesn't exist? 
-- The Edge Function will be doing the insertion. If the Edge Function allows the user to trigger it, 
-- it usually acts with the user's auth token OR service role depending on how client is initialized.
-- We'll assume the Edge Function uses a SERVICE_ROLE client to write to this global table.

-- Create Trigger to automatically update updated_at
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON plant_species_care_guides
  FOR EACH ROW EXECUTE PROCEDURE extensions.moddatetime(updated_at);
